color0 #291416
color1 #f3192f
color2 #f65566
color3 #f5863d
color4 #f5e23d
color5 #f98692
color6 #f9b386
color7 #f3f2f2
color8 #756162
color9 #f3192f
color10 #f65566
color11 #f5863d
color12 #f5e23d
color13 #f98692
color14 #f9b386
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291416
background            #291416
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371b1d
active_border_color   #f65566
inactive_border_color #371b1d
url_color             #f65566

active_tab_foreground   #25181a
active_tab_background   #f65566
inactive_tab_foreground #b6afaf
inactive_tab_background #371b1d
cursor_trail_color      #b6afaf
